<a href="https://colab.research.google.com/github/TusharZalte2208/Food-Ordering-System-GUI-using-Python/blob/main/ReviseNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [2]:
y=[1,2,3,4]
print(y)

[1, 2, 3, 4]


In [3]:
print(type(x))
print(type(y))

<class 'numpy.ndarray'>
<class 'list'>


In [7]:
a=([1,2,"hello"])
print(a)

[1, 2, 'hello']


In [13]:
%timeit [i**4 for i in range(1,9)]
%timeit [(i**4 for i in range(1,9))]
%timeit np.arange(1,9)**4

774 ns ± 12.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
624 ns ± 92.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
2.8 µs ± 613 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Arrays


In [14]:
import numpy as np
y=[1,2,3,4]
x=np.array(y)
print(type(x))
print(type(y))

<class 'numpy.ndarray'>
<class 'list'>


In [17]:
l=[]
for i in range(1,5):
  a=int(input("Enter an integer:"))
  l.append(a)

print(np.array(l))
print(type(np.array(l)))

Enter an integer:45
Enter an integer:56
Enter an integer:548
Enter an integer:454
[ 45  56 548 454]
<class 'numpy.ndarray'>


In [20]:
arr2=np.array([[1,2,3,4],[4,3,2,1]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4]
 [4 3 2 1]]
2


In [21]:
arr3=np.array([[[1,2,3,4],[4,5,6,7],[8,5,9,9]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3 4]
  [4 5 6 7]
  [8 5 9 9]]]
3


In [27]:
arr10=np.array([1,2,4,5],ndmin = 10)
print(arr10)
print(arr10.ndim)

[[[[[[[[[[1 2 4 5]]]]]]]]]]
10


In [32]:
arr0=np.zeros(4)
print(arr0)
print()
arr00=np.zeros((4,5))
print(arr00)

[0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [33]:
arr1=np.ones(4)
arr11=np.ones((4,5))
print(arr1)
print()
print(arr11)

[1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
arr_dia=np.eye(4,7)
print(arr_dia)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


In [38]:
arr_em=np.empty(4)
print(arr_em)

[1. 1. 1. 1.]


In [41]:
arr_ran=np.arange(10)
print(arr_ran)
arr_ran1=np.arange(10)
print(arr_ran1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [47]:
arr_lin=np.linspace(1,10,num=5)
print(arr_lin)
arr_lin=np.linspace(1,10,num=4)
print(arr_lin)
arr_lin=np.linspace(1,10,num=3)
print(arr_lin)
arr_lin=np.linspace(1,10,num=2)
print(arr_lin)

[ 1.    3.25  5.5   7.75 10.  ]
[ 1.  4.  7. 10.]
[ 1.   5.5 10. ]
[ 1. 10.]
